-- Migration: Anonymous Hints Feature

-- 1. Create anonymous_hints table
CREATE TABLE IF NOT EXISTS public.anonymous_hints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_user UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  to_user UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  hint_text TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CHECK (from_user <> to_user),
  CHECK (char_length(hint_text) > 0 AND char_length(hint_text) <= 200)
);

-- 2. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_hints_to_user ON public.anonymous_hints(to_user, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_hints_from_user ON public.anonymous_hints(from_user);

-- 3. Enable RLS
ALTER TABLE public.anonymous_hints ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policy: Users can only view hints sent TO them
-- IMPORTANT: They cannot see who sent it (from_user is hidden)
CREATE POLICY "Users can view received hints"
ON public.anonymous_hints
FOR SELECT
USING (auth.uid() = to_user);

-- Note: No INSERT policy - hints are sent via RPC only for validation


-- 5. RPC Function: Send Anonymous Hint
CREATE OR REPLACE FUNCTION send_anonymous_hint(target_id UUID, hint_message TEXT)
RETURNS jsonb AS $$
DECLARE
  current_uid UUID;
  has_selected BOOLEAN;
BEGIN
  current_uid := auth.uid();
  
  -- A. Validation: Cannot send hint to yourself
  IF current_uid = target_id THEN
    RAISE EXCEPTION 'Cannot send hint to yourself';
  END IF;
  
  -- B. Validation: Must have selected this user (either liked or matched)
  SELECT EXISTS (
    SELECT 1 FROM public.likes WHERE from_user = current_uid AND to_user = target_id
    UNION
    SELECT 1 FROM public.matches WHERE 
      (user1 = LEAST(current_uid, target_id) AND user2 = GREATEST(current_uid, target_id))
  ) INTO has_selected;
  
  IF NOT has_selected THEN
    RAISE EXCEPTION 'You can only send hints to people you have selected';
  END IF;
  
  -- C. Validation: Character limit
  IF char_length(hint_message) = 0 OR char_length(hint_message) > 200 THEN
    RAISE EXCEPTION 'Hint must be between 1 and 200 characters';
  END IF;
  
  -- D. Insert the hint
  INSERT INTO public.anonymous_hints (from_user, to_user, hint_text)
  VALUES (current_uid, target_id, hint_message);
  
  RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 6. Helper RPC: Get My Received Hints (with count)
CREATE OR REPLACE FUNCTION get_my_hints()
RETURNS TABLE (hint_text TEXT, created_at TIMESTAMPTZ) AS $$
BEGIN
  RETURN QUERY
  SELECT h.hint_text, h.created_at
  FROM public.anonymous_hints h
  WHERE h.to_user = auth.uid()
  ORDER BY h.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
